fix: convert jobscheduler to work manager
optimizely/android-sdk pull request #360
Opened 2021-02-02 20:06 UTC by thomaszurkan-optimizely

## Summary
- Deprecate and remove job scheduler in favor of the androidx work manager.
The "why", or other context.

## Test plan

## Issues
- #350

2021-02-03 03:23 UTC, prasannarupan reviewed
Changes looks good. Will wait for the new build to test this out.

2021-02-23 15:04 UTC, mnoman09 submitted a review, later dismissed
Overall looks good. Update headers in all the edited files.

2021-02-23 17:37 UTC, jaeopt requested changes
This fix is great. I see a lot of old messes cleaned up.
See my comments for changes suggestion.

2021-02-23 17:37 UTC, jaeopt commented on test-app/src/main/java/com/optimizely/ab/android/test_app/SplashScreenActivity.kt
> +        applicationContext.registerReceiver(eventRescheduler, IntentFilter(WifiManager.WIFI_STATE_CHANGED_ACTION))
Move this to AndroidManifest "intent-filter" of EventRescheduler like other intents.

2021-02-23 18:01 UTC, jaeopt commented on shared/src/main/java/com/optimizely/ab/android/shared/WorkerScheduler.java
> +                    TimeUnit.MILLISECONDS);
Is this going to retry forever? There should be a way to set the max retries like 3?

2021-02-23 20:49 UTC, thomaszurkan-optimizely commented on event-handler/src/main/java/com/optimizely/ab/android/event_handler/EventRescheduler.java
> +        } else if (broadcastIntent.getAction().equals(WifiManager.WIFI_STATE_CHANGED_ACTION)) {
I, it is registered through register service api in app (look at splash application)

2021-02-23 20:51 UTC, thomaszurkan-optimizely commented on datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileRescheduler.java
>                 if (android.os.Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
No, in cases of a reboot or reload the datafile rescheduler is needed because jobs are not consistent.

2021-02-23 20:55 UTC, thomaszurkan-optimizely commented on test-app/src/main/java/com/optimizely/ab/android/test_app/SplashScreenActivity.kt
> +        applicationContext.registerReceiver(eventRescheduler, IntentFilter(WifiManager.WIFI_STATE_CHANGED_ACTION))
No, that has Ben deprecated. You use register receiver.

2021-02-23 20:55 UTC, thomaszurkan-optimizely commented on shared/src/main/java/com/optimizely/ab/android/shared/WorkerScheduler.java
> +                    TimeUnit.MILLISECONDS);
It does that automatically.

2021-02-23 23:06 UTC, thomaszurkan-optimizely commented on datafile-handler/src/main/java/com/optimizely/ab/android/datafile_handler/DatafileLoader.java
> +                logger.info("Refreshing data file");
This was done on purpose.  The reason is that the save is synched on the shared preferences and showed a noticeable delay in startup times (customers complained).

2021-02-24 17:15 UTC, jaeopt approved these changes
LGTM

2021-02-24 19:42 UTC, santosh399762 approved these changes

2021-02-24 20:05 UTC, merged