chore: add kotlin sample codes
optimizely/android-sdk pull request #404
Opened 2022-01-31 23:14 UTC by jaeopt

## Summary
- Add Kotlin sample codes

2022-02-01 14:42 UTC, mnoman09 requested changes
Over all looks good. Just added some minor suggestions.

2022-02-01 14:42 UTC, mnoman09 commented on test-app/src/main/java/com/optimizely/ab/android/test_app/Samples/APISamplesInJava.java
> +                .withSDKKey("FCnSegiEkRry9rhVMroit4")
Just a suggestion. Can we move sdk key to a variable instead of hardcoding it in every function. It would be easier for user to change.

2022-02-01 14:42 UTC, mnoman09 commented on test-app/src/main/java/com/optimizely/ab/android/test_app/Samples/APISamplesInJava.java
> +        OptimizelyManager optimizelyManager = OptimizelyManager.builder()
Can we move initialization of optimizely manager to one function and use it in all the functions so that usage of decide and other functions become more clear.

2022-02-01 14:42 UTC, mnoman09 commented on test-app/src/main/java/com/optimizely/ab/android/test_app/Samples/APISamplesInJava.java
> +        List<OptimizelyDecideOption> defaultDecideOptions = Arrays.asList(OptimizelyDecideOption.DISABLE_DECISION_EVENT);
can we add a comment on it. That when a user should use defaultDecideOptions and when he should pass decideOption in function

2022-02-01 14:42 UTC, mnoman09 commented on test-app/src/main/java/com/optimizely/ab/android/test_app/Samples/APISamplesInJava.java
> +            String vs = null;
```suggestion
            String variableString = null;
```

2022-02-01 14:42 UTC, mnoman09 commented on test-app/src/main/java/com/optimizely/ab/android/test_app/Samples/APISamplesInJava.java
> +            Log.d("Samples", "decision: " + decision);
I don't think that decision object can be logged in this way. I think it should be decision.toString() just to be sure.

2022-02-01 14:42 UTC, mnoman09 commented on test-app/src/main/java/com/optimizely/ab/android/test_app/Samples/APISamplesInJava.java
> +            System.out.println("[OptimizelyConfig] revision = " + config.getRevision());
can we make it consistent and use either sout or log.d as above we were using log.d and now we are using sout.

2022-02-01 18:02 UTC, Mat001 requested changes

2022-02-01 19:42 UTC, jaeopt commented on test-app/src/main/java/com/optimizely/ab/android/test_app/Samples/APISamplesInJava.java
> +                .withSDKKey("FCnSegiEkRry9rhVMroit4")
The goal of these sample codes is to copy-paste to the doc pages, so I'll keep this style to follow doc requirements. I'll clean up inconsistent sdkkey names.

2022-02-01 20:09 UTC, jaeopt commented on test-app/src/main/java/com/optimizely/ab/android/test_app/Samples/APISamplesInJava.java
> +        // With the new Android O differences, you need to register the
I think it makes sense to android developers :)

2022-02-01 20:10 UTC, jaeopt commented on test-app/src/main/java/com/optimizely/ab/android/test_app/Samples/APISamplesInJava.java
> +                .withSDKKey("SDK_KEY_HERE")
I fixed them to use all <Your_SDK_Key>" consistently.

2022-02-01 20:14 UTC, jaeopt commented on test-app/src/main/java/com/optimizely/ab/android/test_app/Samples/APISamplesInJava.java
> +        OptimizelyManager optimizelyManager = OptimizelyManager.builder()
I understand it's redundant. I'd keep this way for easy copy-and-paste for docs :)

2022-02-01 21:13 UTC, Mat001 approved these changes
lgtm

2022-02-03 17:54 UTC, mnoman09 commented
lgtm

2022-02-03 17:55 UTC, mnoman09 approved these changes
lgtm

2022-02-03 18:01 UTC, merged