Feat: Removed travis yml and added git action support
optimizely/android-sdk pull request #411
Opened 2022-03-17 12:41 UTC by mnoman09

## Summary
- 

## Test plan

## Issues
- "THING-1234" or "Fixes #123"

2022-03-17 22:23 UTC, jaeopt requested changes
Looks great! I have a couple of suggestions/clarification.
Also please fix the PR title (it should be "chore: remove...") and description (empty)

2022-03-17 22:23 UTC, jaeopt commented on .github/workflows/android.yml
> +        api-level: [21, 25, 26, 29]
I understand that github has an issue supporting AVD 31+. 
Can we change "compile_sdk_version" to 31 (no need for "target_sdk_version") since it's required to run other fix?

2022-03-17 22:23 UTC, jaeopt commented on .github/workflows/android.yml
> +        cache: gradle
These steps are repeated for all tasks. Just wondering if we can factor out as a function to simplify this workflow file. github needs to improve it :)

2022-03-18 18:21 UTC, mnoman09 commented on .github/workflows/android.yml
> +        api-level: [21, 25, 26, 29]
Yes I think we can change android compile sdk version to 31 it should cause no problem. As we already tested that on PR #406

2022-03-18 18:25 UTC, mnoman09 commented on .github/workflows/android.yml
> +        cache: gradle
Sure we can refactor it and move to seperate yaml then use it as uses. As of right now I don't there is any way to reuse the steps by keeping it in same file.

2022-03-21 14:40 UTC, mnoman09 commented on .github/workflows/android.yml
> +        cache: gradle
I think with current implementation it is difficult to add reusable workflow so can we refactor it later if possible?

2022-03-21 15:44 UTC, jaeopt commented on .github/workflows/android.yml
> +        cache: gradle
Sounds good to me!

2022-03-24 11:27 UTC, mnoman09 commented
> @mnoman09 I see unit tests fail. Can we try to revert the last commit and then upgrade compile_sdk_version only (keeping target_sdk_version to 29)? The fix to support target_sdk_version 31+ will be handled in a separate PR (#400).

I made the changes as requested.

2022-03-24 18:15 UTC, jaeopt approved these changes
LGTM

2022-03-24 18:42 UTC, merged