feat(ATS): add vuid manager
optimizely/android-sdk pull request #431
Opened 2022-09-12 18:34 UTC by jaeopt

## Summary
Add VuidManager which will create and manage a vuid:
 
- create a random vuid if it cannot be found in the device with the required format.
- "vuid_" + 32 hexadecimal string (UUID with all "-"s removed). 
- all lowercases ("vuid_330e05cad15746d9af8a75b8d1050a87")
- SDK will reuse the same vuid (saving to and retrieving from a persistent storage when the client application starts).
- SDK will support a single vuid shared by multiple SDK instances (thread-safe)
- ODP module added

## Test plan
- add unit tests

## Issues
- [OASIS-8548](https://optimizely.atlassian.net/browse/OASIS-8548)

2022-09-23 13:54 UTC, opti-jnguyen commented on odp/src/androidTest/java/com/optimizely/ab/android/odp/VuidManagerTest.kt
> +    fun cleanSheredPrefs() {
Should this be `cleanSharedPrefs`?
Typo in "Shered" to "Shared".

2022-09-23 14:09 UTC, opti-jnguyen commented on event-handler/src/androidTest/java/com/optimizely/ab/android/event_handler/EventDAOTest.java
> +        context.deleteDatabase(String.format(EventSQLiteOpenHelper.DB_NAME , "1"));
Out of curiosity, why was the assertion removed here?

2022-09-23 14:17 UTC, opti-jnguyen commented on test-app/src/main/java/com/optimizely/ab/android/test_app/NotificationService.kt
> +class
Is `class` intentionally on a separate line here?

2022-09-23 14:26 UTC, opti-jnguyen requested changes
Overall LGTM besides the probable typo with `shered`.

Food for thought - what do you think about abstracting out VUID as its own class, separate from VUIDManager?

Was fun re-visiting Kotlin!

2022-09-23 20:31 UTC, jaeopt commented on event-handler/src/androidTest/java/com/optimizely/ab/android/event_handler/EventDAOTest.java
> +        context.deleteDatabase(String.format(EventSQLiteOpenHelper.DB_NAME , "1"));
For cleaning up with remaining database from other tests, the teardown is also called when starting each test. So assert is not true always.

2022-09-23 20:32 UTC, jaeopt commented on test-app/src/main/java/com/optimizely/ab/android/test_app/NotificationService.kt
> +class
Not intentional. restored :)

2022-09-26 19:22 UTC, opti-jnguyen approved these changes
LGTM

2022-12-16 17:52 UTC, merged