feat(ATS): update OptimizelyManager/OptimizelyClient for ODP integration
optimizely/android-sdk pull request #444
Opened 2023-01-09 18:59 UTC by jaeopt

## Summary
Extends top level (OptimizelyManager/OptimizelyClient) to provide public APIs and connect to the core ATS features provided by the integrated Java-SDK.

Add new APIs:
- OptimizelyClient.createUserContext() without userId
- OptimizelyClient.sendOdpEvent()

ODP Configuration (OptimizelyManager.Builder)
- SegmentCache configuration
- ODPClient timeout configuration
- Disable ODP

## Test plan
- Add new unit tests covering new APIs

## Issues
- FSSDK-8549
- FSSDK-8695

2023-01-12 16:52 UTC, mnoman09 requested changes
Overall looks good. Added few comments. I am not seeing custom cache support in this PR, so are we going to add it in a separate PR?

2023-01-12 16:52 UTC, mnoman09 commented on android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
> +    @NonNull private final List<OptimizelyDecideOption> defaultDecideOptions;
Why did we change it to Nonnull, because I am still seeing it nullable at other places?

2023-01-12 16:52 UTC, mnoman09 commented on android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
> +        private long odpSegmentCacheSize = 100L;
I think instead of long we should use int data type because eventually we are parsing it to int. Same goes for odpSegmentCacheTimeoutInSecs

2023-01-12 16:52 UTC, mnoman09 commented on android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerBuilderTest.java
> +    public void testBuildWithODP_defautSegmentFetchTimeout() throws Exception {
```suggestion
    public void testBuildWithODP_defaultSegmentFetchTimeout() throws Exception {
```

2023-01-12 16:52 UTC, mnoman09 commented on android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerBuilderTest.java
> +    public void testBuildWithODP_defaultCache() throws Exception {
```suggestion
    public void testBuildWithODP_defaultCacheSize() throws Exception {
```

2023-01-12 16:52 UTC, mnoman09 commented on android-sdk/src/test/java/com/optimizely/ab/android/sdk/OptimizelyManagerBuilderTest.java
Update the header of this file.

2023-01-12 16:52 UTC, mnoman09 commented on odp/src/main/java/com/optimizely/ab/android/odp/ODPSegmentClient.kt
>          var CONNECTION_TIMEOUT = 10 * 1000
can we add comment here to show its unit, "ms".

2023-01-12 16:52 UTC, mnoman09 commented on android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java
> +            if (this.vuid != null) {
Are we only going to trigger sendOdpEvent for client_intialized when vuid is given instead of user id or is it for both cases? Also if the vuid will be inserted by java sdk then what will this check ensure?

2023-01-12 18:35 UTC, jaeopt commented
> Overall looks good. Added few comments. I am not seeing custom cache support in this PR, so are we going to add it in a separate PR?

@mnoman09 it's not expected that android-sdk clients will customize the cache (other than size and timeout), so not supported until we see demands.

2023-01-12 18:43 UTC, jaeopt commented on android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
> +    @NonNull private final List<OptimizelyDecideOption> defaultDecideOptions;
A good catch. I might be confused. It has been restored back to Nullable.

2023-01-12 19:09 UTC, jaeopt commented on android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyManager.java
> +        private long odpSegmentCacheSize = 100L;
I changed all odp numbers to int.

2023-01-12 19:15 UTC, jaeopt commented on android-sdk/src/main/java/com/optimizely/ab/android/sdk/OptimizelyClient.java
> +            if (this.vuid != null) {
A good catch. I remove vuid null checking.

2023-01-12 19:27 UTC, jaeopt commented
@mnoman09 all suggestions addressed. Please review again.

2023-01-16 10:02 UTC, mnoman09 approved these changes
lgtm.

2023-01-17 17:01 UTC, merged